### PR TITLE
Add quality selection and add option to download current episode

### PR DESCRIPTION
**Pull request by yoru-aniro**

### CODE REVIEW

**Comment by AdvMaple** [comment]
image
Bug: There isn't option for quality select

**Comment by AdvMaple** [comment]
image
Bug: And I don't know how "Generate Links for this Ep" work. Error when press.

**Comment by yoru-aniro** [comment]
Seems like there're bugs when you're not login.

For `Generate Links for this EP` is an options for download just the current ep you're playing. It's too annoying when you want to download for just 1 ep but you have to generate for 10 or 20 eps.

**Comment by yoru-aniro** [comment]
@AdvMaple I just update the code. It should work well now.

**Comment by AdvMaple** [comment]
Generate Link for this ep doesn't work when you initialy load the series.
Episode 1 of most series will not have ep_id in their URL.
Here the url:
image

What I console.log out:
image

If you are trying to get user current episode, I suggest parsing the breadcrumb span:
image

Other than that, the choose quality is working now.

**Comment by yoru-aniro** [comment]
Okay, I will check if it included the ep_id or not

**Comment by yoru-aniro** [comment]
@AdvMaple I fixed the get current issue when `ep_id` is not existed on pathname.

I do this by get the active class of the ep list and get the id from there.

**Comment by yoru-aniro** [comment]
Now the UI is supported multiple languages based on the app language (Currently EN and TH, the other will fallback to EN).
You can add more translation if you wanted to.

**Comment by AdvMaple** [comment]
I will just revert the update url for the plugin

**Pull request merged**
