### PR TITLE
Add subtitle format support

### PR DESCRIPTION
**Pull request by xubmuajkub**
I've made an update so that we can directly get the SRT formatted subtitle.

### CODE REVIEW

**Comment by AdvMaple** [comment]
Can it be read using Aegisub or SubtitleEdit? The json file is formatted so it can't be read by Aegisub.
SubtitleEdit can read bilibili json format so I want to download the original json. This can be set as an option in a modal, rather than hard coding.

**Comment by xubmuajkub** [comment]
> Can it be read using Aegisub or SubtitleEdit? The json file is formatted so it can't be read by Aegisub. SubtitleEdit can read bilibili json format so I want to download the original json. This can be set as an option in a modal, rather than hard coding.

@AdvMaple Yes, this can be edited via Aegisub and so on.

I will create an option for user to select like subtitle if needed.

**Comment by AdvMaple** [comment]
@xubmuajkub Yes, create a modal so users can choose what type of subtitle to download is preferred. You can group "language" option with "subtitle type" inside the modal.

**Comment by xubmuajkub** [comment]
@AdvMaple I updated the UI now users can select JSON, SRT, or VTT format as their need.

On download sub button click now resetting the old links before appending new links.

**Comment by AdvMaple** [comment]
I'll check it out when I back home

**Comment by AdvMaple** [comment]
image
Bug: Change language after links have been rendered. File extension become null

**Comment by AdvMaple** [comment]
I'm gonna merge this into main branch after I added some fixes and aditional features. In the mean time, I will change the README install link to one of the feature branch.
I also want to do some reformat and refactoring.

**Comment by xubmuajkub** [comment]
Thanks

**Pull request merged**
